import './globals.css';
import localFont from 'next/font/local';
import { Noto_Sans_Mono } from 'next/font/google';

const calibreFont = localFont({
  src: [
    {
      path: '../../public/font/calibre/CalibreRegular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/font/calibre/CalibreRegularItalic.otf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../../public/font/calibre/CalibreMedium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/font/calibre/CalibreMediumItalic.otf',
      weight: '500',
      style: 'italic',
    },
    {
      path: '../../public/font/calibre/CalibreBold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/font/calibre/CalibreBoldItalic.otf',
      weight: '700',
      style: 'italic',
    },
  ],
  variable: '--font-calibre',
});

const notoFont = Noto_Sans_Mono({
  variable: '--font-noto',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${notoFont.variable} ${calibreFont.variable} font-sans`}>
      <body>{children}</body>
    </html>
  );
}
